# POST http://127.0.0.1:8000/api/notifications/1/read
# Accept: application/json
# Authorization: Bearer

# {
#     "customer_id":2,
#     "status":"canceled",
#     "items":[
#         {
#             "product_name":"هاتف ذكي N",
#             "price":300.00,
#             "quantity":1
#         },
#         {
#             "product_name":"سماعات رأس N",
#             "price":75.00,
#             "quantity":2
#         }
#     ]
# }

# POST http://127.0.0.1:8000/api/customers
# Accept: application/json
# Content-Type: application/json

# {
#   "name": "maya",
#   "phone": "0915184"
# }
# POST http://127.0.0.1:8000/api/orders
# Content-Type: application/json

# {
#   "customer_id": 1,
#   "items": [
#     {
#       "product_name": "لابتوب A",
#       "price": 500.00,
#       "quantity": 2
#       // Subtotal يجب أن يكون 1000.00
#     },
#     {
#       "product_name": "ماوس لاسلكي",
#       "price": 25.50,
#       "quantity": 4
#       // Subtotal يجب أن يكون 102.00
#     }
#   ]
#   // Order.total يجب أن يكون 1102.00
# }
# POST http://127.0.0.1:8000/api/login
# Content-Type: application/json

# {
#     "email": "test@example.com",
#     "password": "123456"
#     }
# POST http://127.0.0.1:8000/api/notifications/51ba3af0-0060-47d2-a5be-6fb65cb1d322/read
# Accept: application/json
# Authorization: Bearer

# GET http://127.0.0.1:8000/api/notifications
# Accept: application/json
# Authorization: Bearer 3|t0Zz9QKwkNxTZoQ5wGMGwdg6ETScSOqZC5dGaNba31ad37e0

# PATCH   http://127.0.0.1:8000/api/orders/1/status
# Accept: application/json
# Content-Type:application/json
# Authorization:Bearer 3|t0Zz9QKwkNxTZoQ5wGMGwdg6ETScSOqZC5dGaNba31ad37e0

# {
#     "status": "pending"
# }

# (User Created)
# POST http://127.0.0.1:8000/api/users/store
# Content-Type: application/json
# Accept: application/json

# {
#     "name": "Ahmad Test",
#     "email": "ahmad.test@example.com",
#     "password": "password123",
#     "password_confirmation": "password123"
# }

# ####
#
# PATCH http://127.0.0.1:8000/api/orders/1/status
# Authorization: Bearer
# Content-Type: application/json
# Accept: application/json

# {
#     "status": "paid"
# }


# POST http://127.0.0.1:8000/api/payment/process
# Authorization: Bearer 17|nRdyg8s9oh9PamMCfuFQFpw1HgZ7cMEDEBrys7Ct1be385fa
# Content-Type: application/json
# Accept: application/json

# {
#     "amount": 1
# }
# GET http://127.0.0.1:8000/api/notifications
# Authorization: Bearer
# Accept: application/json
